name: Update Toggl Stats

on:
  schedule:
    - cron: '0 18 * * *'  # Обновлять каждый день в 18:00 UTC
  workflow_dispatch:       # Можно запустить вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install axios
      
      - name: Generate Toggl Card
        env:
          TOGGL_API_KEY: ${{ secrets.TOGGL_API_KEY }}
        run: node src/generate-card.js
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add toggl-stats.svg
          git commit -m "Обновление статистики Toggl"
          git push